# Generated by Django 2.1.1 on 2018-10-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('Multa_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Muni_id', models.CharField(max_length=200)),
                ('Valor', models.IntegerField()),
                ('Fecha_emision', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('Muni_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='P_circulacion',
            fields=[
                ('PCir_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Fecha_vencimiento', models.DateField()),
                ('Precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Rut', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido_P', models.CharField(max_length=200)),
                ('Apellido_M', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('Fecha_nacimimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='R_tecnica',
            fields=[
                ('RTec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Vigencia', models.DateField()),
                ('num_chasis', models.IntegerField()),
                ('num_motor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='S_obligatorio',
            fields=[
                ('SObl_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('Sucursal_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=200)),
                ('Munin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Municipalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('Nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Modelo', models.CharField(max_length=200)),
                ('Marca', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('Num_chasis', models.IntegerField()),
                ('Num_motor', models.IntegerField()),
                ('Rut_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='s_obligatorio',
            name='Patente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Vehiculo'),
        ),
        migrations.AddField(
            model_name='r_tecnica',
            name='Patente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Vehiculo'),
        ),
        migrations.AddField(
            model_name='p_circulacion',
            name='Patente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Vehiculo'),
        ),
        migrations.AddField(
            model_name='p_circulacion',
            name='Sucursal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Sucursal'),
        ),
        migrations.AddField(
            model_name='multa',
            name='Patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tabla.Vehiculo'),
        ),
    ]
