# Generated by Django 2.1.1 on 2018-10-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Fecha_nacimimento',
            field=models.DateField(blank=True),
        ),
    ]
