# Generated by Django 2.1.1 on 2018-11-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tabla', '0003_auto_20181029_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='Hijos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
