# Generated by Django 2.1.1 on 2018-11-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tabla', '0004_persona_hijos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='Hijos',
        ),
    ]
